# Generated by Django 5.0 on 2024-03-27 16:58

import apps.panel.utils
import django.core.files.storage
import django.core.validators
import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\User\\Desktop\\Nest\\DEV\\media\\files'), upload_to=apps.panel.utils.upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg', 'pdf', 'doc', 'docx', 'xls', 'xlsx', 'ppt', 'pptx'])])),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SEOData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, help_text='SEO title', max_length=255, null=True)),
                ('description', models.TextField(blank=True, help_text='Meta description for SEO', null=True)),
                ('keywords', models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='SEO-friendly URL', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='slice',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\User\\Desktop\\Nest\\DEV\\media/icons/'),
        ),
        migrations.AlterField(
            model_name='slice',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='C:\\Users\\User\\Desktop\\Nest\\DEV\\media/images/'),
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('items_object_id', models.PositiveIntegerField()),
                ('order', models.JSONField(blank=True, null=True)),
                ('items_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField()),
                ('parent_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='panel.template')),
            ],
        ),
        migrations.CreateModel(
            name='TextContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', tinymce.models.HTMLField(blank=True, null=True)),
                ('keywords_block', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.DeleteModel(
            name='Gallery',
        ),
    ]
