# Generated by Django 5.0 on 2024-03-04 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0020_templantarez_galleryset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='pp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='page_gallery', to='panel.page'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='ps',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='slice_gallery', to='panel.slice'),
        ),
        migrations.AlterField(
            model_name='galleryset',
            name='imgset',
            field=models.ManyToManyField(related_name='gallery_sets', to='panel.gallery'),
        ),
        migrations.CreateModel(
            name='GallerySetThrough',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gallery', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.gallery')),
                ('galleryset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='panel.galleryset')),
            ],
            options={
                'unique_together': {('galleryset', 'gallery')},
            },
        ),
    ]
